namespace POS.Core.Entities.OrderEntity;

public class Orders:BaseEntity
{
    public int BranchID { get; set; }
    public int OrderID { get; set; }
    public string? BranchName { get; set; }
    public ShiftHandover? Shift { get; set; }
    public int? ShiftID { get; set; } = 1;
    public int? CashierID { get; set; }
    public string? CashierName { get; set; }
    public DateTime? OrderDate { get; set; }
    public OrderTypes? OrderType { get; set; } 
    public OrderStates? OrderState { get; set; }
    public string? DeliveryCompany { get; set; }
    public int? TakerID { get; set; }
    public string? TakerName { get; set; }
    public string? TitleName { get; set; }
    public int? CustomerID { get; set; }    
    public string? CustomerName { get; set; }
    public string? Phone1 { get; set; }
    public string? Phone2 { get; set; }
    public string? HomeNum { get; set; }
    public string? StreetName { get; set; }
    public string? FloorNum { get; set; }
    public string? ApartmentNum { get; set; }
    public string? AddressNotice { get; set; }
    public int? ZoneID { get; set; }
    public string? ZoneName { get; set; }
    public decimal? ZoneBonus { get; set; }
    public string? DispatchID { get; set; }
    public int? DriverID { get; set; }
    public string? DriverName { get; set; }
    public DateTime? AssignTime { get; set; }
    public DateTime? BackTime { get; set; }
    public int? TableID { get; set; }
    public string? TableName { get; set; }
    public string? TableState { get; set; }
    public int? WaiterID { get; set; }
    public string? WaiterName { get; set; }
    public decimal? Subtotal { get; set; }
    public decimal? Tax { get; set; }
    public decimal? Service { get; set; }
    public decimal? DeliveryFees { get; set; }
    public decimal? Discount { get; set; }
    public decimal? DiscountedItems { get; set; }
    public decimal? FreeItems { get; set; }
    public decimal? TotalDiscount { get; set; }
    public PaymentMethod? PaymentMethod { get; set; }
    public decimal? GrandTotal { get; set; }
    public decimal? Paid { get; set; }
    public decimal? Remain { get; set; }
    public decimal? ReservationPaid { get; set; }
    public decimal? ReservationRemain { get; set; }
    public DateTime? ScheduleDateTime { get; set; }
    public int? CustomerCount { get; set; }
    public string? DiscountType { get; set; }
    public decimal? DiscountPercentage { get; set; }
    public int? DiscountBy { get; set; }
    public string? DiscountByName { get; set; }
    public DateTime? DiscountTime { get; set; }
    public string? DiscountReason { get; set; }
    public bool? WithoutService { get; set; }
    public bool? WithoutTax { get; set; }
    public bool? WithoutDeliveryFees { get; set; }
    public string? OrderNotice { get; set; }
    public decimal? VoidAmount { get; set; }
    public int? VoidBy { get; set; }
    public string? VoidByName { get; set; }
    public DateTime? VoidTime { get; set; }
    public string? VoidReason { get; set; }
    public int? VoidCount { get; set; }
    public decimal? TotalVoid { get; set; }
    public int? PrintCount { get; set; }
    public DateTime? KitchenOutTime { get; set; }
    public DateTime? PackingOutTime { get; set; }
    public DateTime? ClosingTime { get; set; }
    public int? TakeawayCustomerId { get; set; }
    public TakeawayCustomer? TakeawayCustomer { get; set; }
    public string? TakeawayCustomerName { get; set; }
    public string? TakeawayCustomerPhone { get; set; }
    public ICollection<OrderItemsDetails>? OrderDetails { get; set; } = new List<OrderItemsDetails>();
}   